version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: techstore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techstore
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: techstore_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysqldata:
